- src/main/java/site/bidderown/server/HelloController.java
> [#1] 초기 설정

- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomResponse.java
> [#20] 채팅방 상대방 유저 이름 가져오는 코드 오류 해결

- src/main/java/site/bidderown/server/base/data/NotProd.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomRequest.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomResponse.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/entity/ChatRoom.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
- src/main/java/site/bidderown/server/bounded_context/member/service/MemberService.java
- src/main/resources/application.yml
- src/test/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomServiceTest.java
> [#19] chat room test

- src/main/java/site/bidderown/server/base/base_entity/BaseEntity.java
- src/main/java/site/bidderown/server/bounded_context/chat/entity/Chat.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/entity/ChatRoom.java
- src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
- src/main/java/site/bidderown/server/bounded_context/member/entity/Member.java
> Refactor : SuperBuilder를 제거합니다

- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomDetail.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomRequest.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomResponse.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/entity/ChatRoom.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/repository/ChatRoomRepository.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
- src/main/resources/templates/usr/chat/list.html
- src/test/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomServiceTest.java
close #23 
- 상품 전체 조회
- 상품 페이지에서 채팅하기 버튼으로 갈 때와 상단 아이콘으로 이동할 때 분리
- 상품 상세 조회
@gkfktkrh153
> [#23] chat controller

- src/main/java/site/bidderown/server/base/security/CustomOAuth2UserService.java
- src/main/java/site/bidderown/server/base/security/CustomUserDetailsService.java
- src/main/java/site/bidderown/server/bounded_context/member/entity/Member.java
> [#31] UserDetailService 추가

- build.gradle
- src/main/java/site/bidderown/server/base/data/NotProd.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomRequest.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
- src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
- src/test/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomControllerTest.java
- src/test/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomServiceTest.java
- post 테스트하면 csrf 에러나서 security-test 의존성 추가했습니다.
- issue 31번 먼저 머지하면 item 오류 빼고는 정상 작동합니다.
- 실수로 ItemController에 final 붙인거 롤백 못했습니다;;
> [#30] 채팅방 Controller 테스트

- src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemRequest.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
- src/main/java/site/bidderown/server/bounded_context/item/entity/Image.java
- src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
- src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRepository.java
- src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
- src/test/java/site/bidderown/server/bounded_context/item/Controller/ItemControllerTest.java
#24 Close
- image entity 추가
- item entity, controller, service 수정
> [#24] 상품 CRUD 리팩터링

- src/main/java/site/bidderown/server/base/websocket/WebSocketConfig.java
- src/main/resources/templates/header.html
- src/main/resources/templates/usr/chat/list.html
- src/main/resources/templates/usr/item/home.html
- 소켓 연결 config
- UI에 필요한 header 추가
> [#35] socket configure and vue

- src/main/java/site/bidderown/server/bounded_context/chat/controller/ChatController.java
- src/main/java/site/bidderown/server/bounded_context/chat/controller/dto/ChatRequest.java
- src/main/java/site/bidderown/server/bounded_context/chat/controller/dto/ChatResponse.java
- src/main/java/site/bidderown/server/bounded_context/chat/service/ChatService.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
- 웹소켓을 이용해 채팅을 저장하는 로직을 구현합니다.
> [#36] 채팅 저장 기능 구현

- src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
- src/main/java/site/bidderown/server/bounded_context/item/entity/Image.java
- src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
- src/main/java/site/bidderown/server/bounded_context/item/entity/ItemStatus.java
- src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
- src/test/java/site/bidderown/server/bounded_context/item/Controller/ItemControllerTest.java
close #41 
- 코드 리뷰 사항 수정
- ItemStatus enum class 추가
> [#41] 상품 전체 리팩토링

- src/main/java/site/bidderown/server/bounded_context/bid/controller/BidController.java
- src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidRequest.java
- src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
- src/main/java/site/bidderown/server/bounded_context/bid/entity/Bid.java
- src/main/java/site/bidderown/server/bounded_context/bid/entity/BidResult.java
- src/main/java/site/bidderown/server/bounded_context/bid/repository/BidRepository.java
- src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
- bid(Controller, Service, Repository) 기본 CRUD작업
> [#43] 입찰 도메인에 대한 초기 작업을 진행합니다. 

- src/main/java/site/bidderown/server/base/data/NotProd.java
- src/main/java/site/bidderown/server/bounded_context/HomeController.java
- src/main/java/site/bidderown/server/bounded_context/chat/controller/ChatController.java
- src/main/java/site/bidderown/server/bounded_context/chat/controller/dto/ChatRequest.java
- src/main/java/site/bidderown/server/bounded_context/chat/controller/dto/ChatResponse.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
- src/main/resources/templates/header.html
- src/main/resources/templates/usr/chat/list.html
- src/main/resources/templates/usr/item/home.html
- 채팅 기능 완료
- UI는 80% 정도 완료
- ChatResponse 변경 id -> username
- 일단 auth 제외(thymeleaf-spring-security사용해서 페이지 접근 불가 가능 혹은 JWT 사용해서 ws 헤더에 토큰 넣음)
- item 이슈
- item을 생성하려면 Image가 필요함, Image를 생성하려면 item id가 필요해서 테스트하거나 생성하기 어렵습니다. 
- 제 생각엔 item 정보와 실제 이미지파일을 form으로  같이 받아서 image를 저장하고 저장한 image 엔티티를 저장하는 방법이 좋아보입니다.
@JinseoPark-bd @gkfktkrh153 @PARK-MI-JI
> feature: chat-room-기능-완료

- src/main/java/site/bidderown/server/bounded_context/notification/controller/NotificationController.java
- src/main/java/site/bidderown/server/bounded_context/notification/controller/dto/NotificationDto.java
- src/main/java/site/bidderown/server/bounded_context/notification/entity/Notification.java
- src/main/java/site/bidderown/server/bounded_context/notification/entity/NotificationType.java
- src/main/java/site/bidderown/server/bounded_context/notification/repository/NotificationRepository.java
- src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
- 알림 초기 작업을 진행했습니다.
- DTO부분에 뭘 넣어줘야할지 모르겠어서 일단 비워두고 흐름만 작성했습니다.
- 타입 쪽은 일단 아래처럼 작성은 했는데 다 처리 방식에 따라서 수정해야할 것 같습니다. 
BID("입찰")
SOLDOUT("판매완료")
BID_END("경매종료")
COMMENT("댓글")
> Feature : 알림 초기작업

- src/main/java/site/bidderown/server/ServerApplication.java
- src/main/java/site/bidderown/server/base/data/NotProd.java
- src/main/java/site/bidderown/server/base/event/EventItemNotification.java
- src/main/java/site/bidderown/server/batch/item/config/ItemJobConfiguration.java
- src/main/java/site/bidderown/server/batch/item/listener/BidEndItemWriterListener.java
- src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
- src/main/java/site/bidderown/server/bounded_context/notification/controller/NotificationController.java
- src/main/java/site/bidderown/server/bounded_context/notification/entity/Notification.java
- src/main/java/site/bidderown/server/bounded_context/notification/event_handler/NotificationEventHandler.java
- src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
- EventItemNotification DTO
- NotificationEventHandler 추가
- NotificationService create 메서드 추가
- publisher로 이벤트 전송 및 messagingTemplate로 전송 `/sub/notification/item/{아이템_id}`
- 경매가 끝났을 때 알림 전송, Notification 저장
- 입찰건이 추가되었을 때 알림 전송, Notification 저장
@gkfktkrh153 
- Notification Entity 빌더 추가
- 컨트롤러 잠시 주석 처리했습니다.
- NotificationDto -> NotificationResponse로 하는게 좋을 거 같습니다!
@JinseoPark-bd 
- getBids() 메서드 하나 부탁드립니다!
> [#66] 알림 경매, 입찰건 기능 추가 

- src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
- src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
- src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
close #62  
- item <-> bid 연관관계 추가
- getWinner() 메소드 추가
> [#62] 상품 입찰목록 조회

- src/main/java/site/bidderown/server/bounded_context/comment/controller/CommentController.java
- src/main/java/site/bidderown/server/bounded_context/comment/controller/dto/CommentRequest.java
- src/main/java/site/bidderown/server/bounded_context/comment/controller/dto/CommentResponse.java
- src/main/java/site/bidderown/server/bounded_context/comment/entity/Comment.java
- src/main/java/site/bidderown/server/bounded_context/comment/repository/CommentRepository.java
- src/main/java/site/bidderown/server/bounded_context/comment/service/CommentService.java
> [#64] feature:comment-update 기능추가

- src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemRequest.java
- src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
- src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
#72 
- 경매 기간 수정
- ItemDetailResponse 추가 
---
1. 기존에는 경매 기간을 3일로 정해놓고 expireAt을 생성했는데, ItemRequest에서 받아와서(3, 5, 7)  expireAt을 생성하는 걸로 하고싶었는데 이렇게 하는게 맞을까요??
2. 상품에대한 전체 디테일한 데이터들을 response로 보내주고싶은데, Item 측에서 입찰정보(최저가, 최고가, 입찰수), 댓글(댓글수)를 보내줘도 되나요??
> [#72] 상품 입찰 부분 수정

- src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemListResponse.java
- src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
- src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRepository.java
- src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
#78 
- 상품 검색 (제목, 내용) 완료 
(판매자ID는 추가 예정)
- 상품 리스트, 검색 페이징 처리
> [#78] 상품 검색, 페이징

- src/main/generated/site/bidderown/server/bounded_context/item/entity/QItem.java
- src/main/java/site/bidderown/server/base/data/NotProd.java
- src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BulkInsertBid.java
- src/main/java/site/bidderown/server/bounded_context/bid/repository/BidJdbcRepository.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/BulkInsertItem.java
- src/main/java/site/bidderown/server/bounded_context/item/repository/ItemJdbcRepository.java
- src/main/java/site/bidderown/server/bounded_context/notification/controller/dto/BulkInsertNotification.java
- src/main/java/site/bidderown/server/bounded_context/notification/event_handler/NotificationEventHandler.java
- src/main/java/site/bidderown/server/bounded_context/notification/repository/NotificationJdbcRepository.java
- insert 성능을 개선하기 위해 jdbc를 이용한 bulk insert를 도입합니다.
- Item, Bid, Notification에 대한 bulk Insert를 작성했습니다.
- initData부분과 NotificationEventHandler 부분이 주요 변경점이라 한번씩 확인해보시면 좋을 것 같습니다.
> Feature : bulkInsert도입

- src/main/resources/templates/usr/myPage.html
- src/main/resources/templates/usr/notification/list.html
> [#86] mypage ui작업 + text-color통합

- src/main/java/site/bidderown/server/base/security/SecurityConfig.java
- src/main/java/site/bidderown/server/bounded_context/HomeController.java
- src/main/java/site/bidderown/server/bounded_context/bid/controller/BidController.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomApiController.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
- src/main/java/site/bidderown/server/bounded_context/notification/controller/NotificationController.java
- src/main/java/site/bidderown/server/bounded_context/socket_connection/controller/SocketConnectionController.java
> [#93] home 수정

- src/main/resources/templates/usr/bid/list.html
- src/main/resources/templates/usr/item/create.html
#91 
- 입찰 금액 백원 단위 입렵 처리
- 상품 등록 시 이미지 파일 필수 입력 처리
> [#91] 입찰 단위/상품 등록 이미지

- src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
- src/main/resources/templates/usr/item/detail.html
- src/main/resources/templates/usr/item/home.html
- src/main/resources/templates/usr/my_page.html
- initData 아이템 생성 시 실제 이미지 파일 주입
- view단의 임시 데이터들을 실제 아이템의 이미지로 변경합니다.
> [#97] view단의 임시 데이터들을 실제 아이템의 이미지로 변경

- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemListResponse.java
- src/main/resources/templates/usr/item/detail.html
- src/main/resources/templates/usr/item/home.html
경매가 종료됐거나 판매가 종료된 상품 경매종료 UI추가
> [#101] 경매가 종료됐거나 판매가 종료된 상품 경매종료 UI추가

- src/main/resources/templates/usr/my_page.html
> [#103] mypage 수정

- src/main/java/site/bidderown/server/base/data/NotProd.java
- src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidDetails.java
- src/main/java/site/bidderown/server/bounded_context/bid/entity/Bid.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
- src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
- src/main/java/site/bidderown/server/bounded_context/notification/event_handler/NotificationEventHandler.java
- src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
- src/main/resources/templates/usr/bid/list.html
- src/main/resources/templates/usr/item/detail.html
- src/main/resources/templates/usr/item/home.html
- src/main/resources/templates/usr/my_page.html
- 판매완료 버튼 클릭시 ItemStatus가 SOLDOUT으로 변경
- 아이템에 걸려있는 입찰 모두 FAIL처리
- 입찰의 주인 Bidder에게 알림 실시간 전송
- 입찰하기 폼은 입찰자만 볼 수 있으며 경매중인 상품에서만 볼 수 있음
- 판매완료 버튼은 판매자만 볼 수 있으며 경매중인 상품에서만 볼 수 있음
- 경매종료시 남은시간 표시X
- 마이페이지에서 
- 판매한 상품은 상품 상세로
- 입찰한 상품은 입찰 내역 페이지로 연결
> [#105] 판매완료 후 처리

- src/main/java/site/bidderown/server/base/event/EventSoldOutNotification.java
- src/main/java/site/bidderown/server/base/util/TimeUtils.java
- src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidDetails.java
- src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
변수명 변경과 UI부분은 추후 리팩토링에 반영하겠습니다.
> [#107]공통로직 병합

- src/main/java/site/bidderown/server/base/util/TimeUtils.java
- src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
시간 별 공통 처리를 위한 만료시간 반올림 작업을 진행했습니다.
> [#109]만료시간 반올림

- src/main/java/site/bidderown/server/base/data/NotProd.java
- src/main/java/site/bidderown/server/base/exception/GlobalExceptionHandler.java
- src/main/java/site/bidderown/server/base/util/ImageUtils.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemRequest.java
#100 
- 이미지 아닌 파일 첨부 시 데이터 처리 x
- BindingException  핸들러로 리다이렉트 처리
> [#100] 예외처리

- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomDetail.java
- src/main/resources/templates/usr/chat/list.html
- 채팅방 위 상품 정보를 상품 상세보기 페이지로 연결합니다.
> [#117] 채팅방 위 상품 정보 상품 상세보기 페이지로 연결

- src/main/resources/templates/usr/item/detail.html
- 아이템 상세페이지 사용자 입장
- 경매중인 상품에 대해서는 입찰하기 버튼
- 경매종료 또는 판매완료 상품일 경우에는 입찰 목록페이지 버튼
> [#119] 아이템 상세페이지 버튼 수정

- src/main/resources/templates/usr/form_login.html
> [#122] form-login UI 수정

- src/main/resources/templates/usr/bid/list.html
- 입찰 내역 페이지에서 버튼 생성
- 판매자가 경매중인 상품에 대해 입찰 목록페이지에 접근했을 때 채팅하기 버튼이 보임
- 눌렀을 때 해당 입찰의 입찰자와 채팅 매칭
> 상세정보 페이지 경매 종료일 때 버튼 수정

- src/main/java/site/bidderown/server/batch/BatchScheduler.java
- src/main/resources/application-secret.yml.txt
- src/main/resources/application.yml
- src/main/resources/templates/usr/item/home.html
> refactoring: ready-to-merge

- src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomResponse.java
- src/main/resources/templates/usr/chat/list.html
- BidResponse - itemId제거
- ChatRoomResponse - itemTitle제거 + vue데이터 초기화 부분도 제거
> [#136] 입찰 리팩토링

- src/main/java/site/bidderown/server/bounded_context/chat/controller/ChatApiController.java
- src/main/java/site/bidderown/server/bounded_context/chat/controller/ChatController.java
- src/main/resources/templates/usr/chat/list.html
close #141  
- chat controller, restController 분리
- list.html :  vue 문법 통일
> [#141] 채팅 controller 분리

- src/main/java/site/bidderown/server/bounded_context/bid/controller/BidApiController.java
- src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
- src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
- src/main/resources/templates/usr/bid/list.html
close #151 
- 입찰 삭제 기능 추가
- 입찰 삭제 버튼 생성
> [#151] 입찰 삭제 기능 추가

- src/main/java/site/bidderown/server/bounded_context/bid/controller/BidApiController.java
- src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
권한 비교는 현재 접속중인 유저의 아이디가 삭제하려는 입찰자 아이디와 같은지 비교해요
권한 예외처리는 forbidden으로 해야할 것 같습니다. 
@JinseoPark-bd  확인하시면 바로 머지해주세요!
> 입찰 취소 예외처리

- src/main/resources/application-dev.yml
- src/main/resources/application-test.yml
- src/test/java/site/bidderown/server/bounded_context/bid/controller/BidControllerTest.java
- src/test/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomControllerTest.java
- src/test/java/site/bidderown/server/bounded_context/item/Controller/ItemControllerTest.java
- Test 환경에는 h2 데이터베이스로 설정했습니다.
- 쿼리볼 수 있게 설정하였습니다.
- @ActiveProfile("test")라고 붙이면 application-test.yml이 적용됩니다.
> [#34] test-환경-분리

- src/main/java/site/bidderown/server/batch/BatchScheduler.java
- src/main/java/site/bidderown/server/batch/item/config/ItemJobConfiguration.java
close #171 
- Item은 '경매중'인 상태만 처리
- BId는 '경매종료'인 상태만 처리
> [#171] 스프링 배치 아이템 리더 오류 해결

- src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidDetails.java
- src/main/resources/templates/usr/bid/list.html
- src/main/resources/templates/usr/notification/list.html
- 판매 문구 변경( 가격을 제시한 물건의 판매가 완료되었습니다.)
- bidList itemStatus비교 String -> enum타입으로 변경
> 판매 문구 변경, bidList itemStatus비교 String -> enum타입으로 변경

- src/main/java/site/bidderown/server/base/data/NotProd.java
- src/main/java/site/bidderown/server/bounded_context/bid/controller/BidApiController.java
- src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
#177 
- notProd에서 user1 상품에 user1 입찰 걸려있어서 수정했습니다.
- 입찰 삭제 권한 체크
- 입찰 등록할 때 자기 상품에 입찰 안되도록 권한 체크
> [#177] 입찰 서비스 권한체크

- src/main/java/site/bidderown/server/base/util/ImageUtils.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemRequest.java
- src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
- src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
- src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
- src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest_eui9179.java
close #173 
1. 기본(최신순) 정렬 조회
2. 인기순 정렬 조회
3. 경매종료순 정렬 조회
4. 상품 검색 조회
- 테스트용 이미지 저장 폴더를 따로 만들었습니다. /resources/images/test
- `generateMockImageFile()` 가짜 이미지를 생성
- `createTestItem()` 테스트용 아이템 생성(이미지 저장 경로만 다름)
- `deletetestImage()` 각 테스트마다 `/test` 폴더 안에 있는 이미지 자동 삭제
> [#173] item all sort and search

- src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
1. 판매완료 테스트
2. 판매완료 권한 테스트
3. 판매완료 상태에서 입찰 테스트
> [#180] 판매완료 테스트 코드

- src/main/java/site/bidderown/server/bounded_context/bid/entity/Bid.java
- src/test/java/site/bidderown/server/bounded_context/bid/service/BidServiceTest.java
#155 
- Bid생성 해줄 때 Item의 bids에도 추가
- 입찰 서비스 테스트 코드 작성
> [#155] 입찰 서비스 테스트

- src/main/java/site/bidderown/server/bounded_context/comment/entity/Comment.java
- src/main/java/site/bidderown/server/bounded_context/comment/repository/CommentRepository.java
- src/main/java/site/bidderown/server/bounded_context/comment/service/CommentService.java
- src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRepository.java
- src/test/java/site/bidderown/server/bounded_context/comment/CommentServiceTest.java
1. 생성
2. 상품 삭제 후 댓글 생성
3. 상품 댓글 전체 
4. 삭제
> [#166] 댓글 테스트

- src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
> [#192] ItemServiceTest 오류 해결

- .gitignore
- build.gradle
- src/main/java/site/bidderown/server/base/data/NotProd.java
- src/main/resources/application-rdb.yml.txt
- src/main/resources/application.yml
- application-rdb.yml 파일이 존재하지 않으면 dev가 적용됩니다.
- 존재하면 데이터베이스 부분만 rdb로 적용됩니다.
나중에 배포할 때 application-prod.yml 새로 생성해서 배포하면 됩니다!
> [#194] application-rdb.yml 추가

- .gitignore
- build.gradle
- src/main/java/site/bidderown/server/base/redis/EmbeddedRedisConfig.java
- src/main/java/site/bidderown/server/base/redis/ExpirationListener.java
- src/main/java/site/bidderown/server/base/redis/RedisConfig.java
- src/main/resources/application-db.yml.txt
- src/main/resources/application.yml
redis 설치되어 있는 분은 redis 종료하고 해야됩니다.
redis설치하고 expire를 설정한 key를 넣으면 ExpirationListener의 onMessage() 가 실행됩니다.
> [#199] redis config

- src/main/resources/application-test.yml
> hotFix:test-yml

- src/main/resources/templates/header.html
- src/main/resources/templates/usr/bid/list.html
- src/main/resources/templates/usr/chat/list.html
- src/main/resources/templates/usr/item/detail.html
- src/main/resources/templates/usr/item/home.html
- src/main/resources/templates/usr/notification/list.html
window.location.href = localhost의 형식으로 하드코딩된 코드들을 제거합니다.
> [#221] redirect url 하드코딩 제거

- src/main/java/site/bidderown/server/base/exception/custom_exception/ForbiddenException.java
- src/main/java/site/bidderown/server/bounded_context/bid/controller/BidApiController.java
- src/main/java/site/bidderown/server/bounded_context/bid/controller/BidController.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomApiController.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
- src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
- src/main/java/site/bidderown/server/bounded_context/comment/controller/CommentApiController.java
- src/main/java/site/bidderown/server/bounded_context/member/controller/MemberController.java
- src/main/java/site/bidderown/server/bounded_context/notification/controller/NotificationController.java
- src/main/java/site/bidderown/server/bounded_context/notification/controller/dto/NewCommentNotificationRequest.java
- src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
- src/main/resources/templates/header.html
- src/main/resources/templates/usr/bid/list.html
- src/main/resources/templates/usr/chatroom/list.html
- src/main/resources/templates/usr/item/detail.html
- src/test/java/site/bidderown/server/bounded_context/notification/service/NotificationServiceTest.java
본인 게시물에 본인이 댓글 달았을 때 알림오는 버그 수정
> [#234] newComment 알림 버그 수정

- src/main/resources/templates/import.html
- src/main/resources/templates/usr/item/create.html
- src/main/resources/templates/usr/my_page.html
#266 
- create.html, my_page.html 리팩토링
- import.html은 글씨체 변경할 수도 있을 것 같아서 괜찮은 것 몇 개만 넣어 놨어요
> [#266] 상품 등록, 마이페이지 리팩토링

- src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
> bugFix: lt-적용

- src/main/resources/templates/import.html
- src/main/resources/templates/usr/item/create.html
- src/main/resources/templates/usr/item/detail.html
#281 
- 기존 alert로 되어있던 부분 수정했습니다.
> [#281]입찰 알림 창 UI수정

- src/main/java/site/bidderown/server/ServerApplication.java
- src/main/java/site/bidderown/server/base/base_entity/BaseEntity.java
- src/main/java/site/bidderown/server/base/redis/listener/ExpirationListener.java
- src/main/java/site/bidderown/server/bounded_context/bid/entity/Bid.java
- src/main/java/site/bidderown/server/bounded_context/bid/entitylistener/BidEntityListener.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
- src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemsResponse.java
- src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
- src/main/java/site/bidderown/server/bounded_context/item/entitylistener/ItemEntityListener.java
- src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
- src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRedisRepository.java
- src/main/java/site/bidderown/server/bounded_context/item/service/ItemRedisService.java
- src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
- src/main/resources/application.yml
- src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
redis의 sorted set을 이용하여서 구현하였습니다.
> [#294] 인기도 순 쿼리 개선

- src/main/java/site/bidderown/server/base/scheduler/SchedulerRunner.java
- src/main/java/site/bidderown/server/boundedcontext/item/entitylistener/ItemEntityListener.java
- src/main/java/site/bidderown/server/boundedcontext/item/repository/ItemCustomRepository.java
- src/main/java/site/bidderown/server/boundedcontext/item/service/ItemService.java
**레디스 장애 시 발생할 수 있는 문제**
AOF방식을 통해 모든 데이터를 복구한다는 전제 하에 진행했습니다.
1. 복구 후 만료 기간이 지났지만 처리 안된 데이터 존재 -> 마감 처리
2. 아이템은 등록됐는데 레디스에는 안들어감 -> 트랜잭션 처리
추가로 redis가 죽었다 살아날 때 만료기간 이벤트 로그 옵션이 초기화 되기 때문에 redis.conf파일을 변경해주어야 합니다.
> Refactoring: 레디스 장애 시 임시 대응
